### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#351]
All variables should have a default value. This will guarantee that the variable is always available, even if it is set to null. 

Special case: Date / Time picker should default to NOW

If you submit a form the data object should contain the variable with no value. 

This is wrong:

![image](https://user-images.githubusercontent.com/535300/63598078-b8920900-c573-11e9-9e7f-c5c6f49a6d69.png)

this is correct

![image](https://user-images.githubusercontent.com/535300/63598128-cc3d6f80-c573-11e9-938e-c3e01d830301.png)

**Comment by velkymx** [comment]
@sanjacornelius can you review. This isn't working in Beta 9

**Comment by sanjacornelius** [comment]
@velkymx  Looks like the PR  #364 that was added for this bug was reverted by @chipit24  because of freezing issues when the _Intermediate Message Catch Event_ was selected/highlighted.  We found that the date format `MM/DD/YYYY h:mm A` was causing a few bugs. I created a new PR #413 removing the date formatting and requested @chipit24 to review.
