### ISSUE TITLE
Nested Screen Multi-Page Not Working

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#561]
Use this screen:

[Nested Screen Test.json.txt](https://github.com/ProcessMaker/screen-builder/files/4243138/Nested.Screen.Test.json.txt)

**Result:**
With the exception of an uploaded file, data entered into the nested form screen on the first page does not show up on the second page.

**Expected:**
Data entered into the nested form screen on the first page shows up on the second page.

**Comment by caleeli** [comment]
@velkymx This was caused because the nested-screen in the first tab has a data variable scope of "form_nested_screen_2" and the one in the other page has "form_nested_screen_1", then the data of the first nested-screen was stored in "**form_nested_screen_2**" and the data on the second nexted-screen was stored in "**form_nested_screen_1**"

To solve this confusion, the scope variable was removed from the control in the PR https://github.com/ProcessMaker/screen-builder/pull/588 (TICKET #562 )

**Comment by caleeli** [comment]
![NavigationAndNestdScreens](https://user-images.githubusercontent.com/8028650/75464041-ffb2e980-595c-11ea-84ad-5803858c158c.gif)

This will be fixed by #588

**Comment by ZLTM** [comment]
working on dev
