### ISSUE TITLE
Nested Screen Not Using Existing Data

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#562]
**CURENT BEHAVIOR:**
When using nested screens, the data from a previous screen does not get passed into the nested screen. If the variable is updated in the parent screen it will then populate the child screen. 

**EXPECTED BEHAVIOR:**
The variable needs to be passed on load to the child screen. 

https://www.dropbox.com/s/ca0ptlqvz63doab/NestedVarsNotWorking.mov?dl=0

**Comment by caleeli** [comment]
Since the nested screen has a scope defined (Data Variable=parent), the second field of the nested screen in the video is pointing to: "parent.parent.name" (https://github.com/ProcessMaker/screen-builder/issues/508)
The first "parent" comes from the scope assigned to the nested screen
The second "parent" comes from the "Variable" assigned to the second field inside the nested screen (parent.name).

I purpose to add two new magic variables: "_parent" and "_root"

In a Scoped Nested Screen `_parent` will point to the parent's data. This way if the Nested Screen need to access to the owners variable scope it could use "_parent". Ex.

```
_parent.variable   // Point to a variable in the parent
_parent.customer.variable  // Point to a variable in a scoped nested screen (customer) inside the parent
_parent.company.variable  // Point to a variable in another scoped nested screen (company)
```
For multiple scoped nested screens "_root" will always point to the top-level data. Ex:

- _root    <-- top-level
  - customer
    - location
      - street (variable)
  - company

`_parent` for **location** will be `customer`
`_parent` for **customer** will be `_root`
`_parent` for **company** will be `_root`
`_root` for **location** will be `_root`

If the nested screen is not scoped "_parent" will point to the same parent screen of the owner screen.

- _root    <-- top-level
  - customer
    - location
      - street (variable)
      - (not scoped nested screen 1)
        - name (variable)
  - company
    - (not scoped nested screen 2)
      - name (variable)

`_parent` for the `not scoped nested screen 1` will point to `_customer` (that's location's _parent)
`_parent` for the `not scoped nested screen 2` will point to `_root`

**Comment by velkymx** [comment]
Why can't we just make parent.parent.name into parent.name? I think adding magic variable just adds complexity for complexity sake.

**Comment by caleeli** [comment]
What is parent for you?

**Comment by caleeli** [comment]
The easiest way is add the nested screen without scope variable, so this way it could access directly to the global variables (https://github.com/ProcessMaker/screen-builder/issues/508)

**Comment by ZLTM** [comment]
Still not seeing the values from one screen being shared with a nested one

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/7957742/75779836-c13c7680-5d30-11ea-8167-18a03f5eedac.gif)
