### ISSUE TITLE
Nested Summary Data Formatting Missing

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#564]
![image](https://user-images.githubusercontent.com/535300/75129920-7364a600-5680-11ea-9aa7-c111e101e62f.png)

The data should be formatted just like the other data.

**Comment by chipit24** [comment]
@velkymx Can you please specify exactly how you expect the data to be formatted. Also, can you list the steps needed to set up the form in such a way that the incorrect formatting is displayed.

I set up a simple nested form and the data in the nested form is formatted exactly the same as the data in the parent form. The issue here is not obvious to me.

<img width="571" alt="Screen Shot 2020-02-26 at 5 01 18 PM" src="https://user-images.githubusercontent.com/7561061/75392528-3b48a780-58ba-11ea-9d93-c2e26f39b665.png">

<img width="792" alt="Screen Shot 2020-02-26 at 5 03 12 PM" src="https://user-images.githubusercontent.com/7561061/75392453-118f8080-58ba-11ea-9dc7-c72b19362cbe.png">

**Comment by velkymx** [comment]
I think ideally I'd like to see it like:

key: name.one value: Name 1 Non-nested
key: name.two value: Name 2

**Comment by chipit24** [comment]
@velkymx So you'd like to see the formatting changed for **both** _nested screens_ and _regular screens_? 

This sounds like a new feature; when I see "bug", I assume it worked at some point in the past and apply a slightly different strategy to help fix it (like going back in the git history to see when and how it broke, for example).

If I set up inputs like this:
<img width="241" alt="Screen Shot 2020-02-27 at 2 30 30 PM" src="https://user-images.githubusercontent.com/7561061/75479694-e9f9f000-596d-11ea-9cee-917539103cfc.png">
<img width="231" alt="Screen Shot 2020-02-27 at 2 30 34 PM" src="https://user-images.githubusercontent.com/7561061/75479693-e9f9f000-596d-11ea-9d8d-716969299b14.png">

They generate data like this:
<img width="195" alt="Screen Shot 2020-02-27 at 2 30 42 PM" src="https://user-images.githubusercontent.com/7561061/75479692-e9615980-596d-11ea-97cd-4cce4bb4379d.png">

And produce the following summary:
Summary table:
<img width="760" alt="Screen Shot 2020-02-27 at 2 37 49 PM" src="https://user-images.githubusercontent.com/7561061/75480147-bec3d080-596e-11ea-957e-3f8f6b53bfca.png">

Data:
```json
{
    "names1": [
        "Rob"
    ],
    "names2": {
        "foo": "Rob"
    },
    "form_button_1": null
}
```

And you want the data to be displayed like so?
<img width="875" alt="Screen Shot 2020-02-27 at 2 39 02 PM" src="https://user-images.githubusercontent.com/7561061/75480274-f3d02300-596e-11ea-972d-405e1081c048.png">
