### ISSUE TITLE
Buttons Not Working In Loops

### ISSUE THREAD

**Issue by velkymx** [ProcessMaker/screen-builder#592]
The 'Page Navigation',  'Submit' & 'Add Record' buttons do not work within a Loop component. When selected the page refreshes.

**Comment by chipit24** [comment]
Adding this for completeness: According to https://github.com/ProcessMaker/screen-builder/issues/559, the submit button in nested screens should be hidden.

This leaves two issues: fixing page navigation in nested screens, and fixing the add record functionality in nested screens. I think this should be broken out into two separate issues.

**Comment by chipit24** [comment]
Nested screen record list also appears to work as expected:

![nested_screen_record_list](https://user-images.githubusercontent.com/7561061/75459260-1c472580-594d-11ea-9528-e3ad18b8b395.gif)

**Comment by sanjacornelius** [comment]
@chipit24  Nested screens work fine. The issue is with the Loop component.

<a href="https://www.loom.com/share/31f17e780a9a4ddc9b6f22543a4a1133"> <p>27 February, 2020 - Loom Recording - Watch Video</p> <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/31f17e780a9a4ddc9b6f22543a4a1133-with-play.gif"> </a>

**Comment by chipit24** [comment]
Ah, I wasn't even aware of the Loop component. I was focused on nested screens and mistook "loop" to mean "nested". Thanks @sanjacornelius!

**Comment by chipit24** [comment]
So, this happens because `form-loop` wraps its `vue-form-renderer` in a `form`, and `button`s in a form that don't have a type specified default to `type="submit"`, causing the parent form to submit. And since the form doesn't specify any `action` or `target`, it seems to submit the form to the current page, causing it to reload.
